### ISSUE TITLE
Program Committee Mailing List

### ISSUE THREAD

**Issue by mmoreshead** [cc-archive/cc-summit-2017#1]
Hi @robmyers - we need a mailing list (ibiblio or otherwise) for the summit committee. @alisonanalog  and I would have admin controls.  I think something like gscommittee@ or something like that (open to suggestions).

What else do you need to know?

**Comment by mmoreshead** [comment]
Also, I dunno what settings this repository has but I can't assign or label this issue.

**Comment by rheaplex** [comment]
I've changed the permissions, please try to assign me now?

**Comment by rheaplex** [comment]
Would the committee just be staff or would it be people without a cc.org email address as well?

**Comment by mmoreshead** [comment]
It will be mostly affiliates, a few HQ.

(And that worked, I can assign stuff!)

**Comment by rheaplex** [comment]
Would 2017 Summit Committee be an OK name for it?

**Comment by mmoreshead** [comment]
Sure, that works, just trying to stay away from anything that starts summit@ so that emails don't end up in the wrong spots.

**Comment by rheaplex** [comment]
Gotcha.

**Comment by mmoreshead** [comment]
You're the best, @robmyers.

**Comment by rheaplex** [comment]
:-) See email. :-)
