### ISSUE TITLE
CiviCRM - new user

### ISSUE THREAD

**Issue by alisonanalog** [cc-archive/cc-summit-2017#2]
Hi Rob, 
Could you please set me up as a new user in CiviCRM?
Would it be possible for you and I to chat once I have logged in so I can get a very basic orientation from you?
Thanks!
Alison

**Comment by rebeccakross** [comment]
@alisonanalog, I'm happy to jump in as well if I can be helpful with a quick tour too. I just forwarded you the online trainings I've done and found super useful

**Comment by rheaplex** [comment]
@alisonanalog You should now have an email containing instructions for logging in as your new user. If you have any problems logging in just let me know.

For orientation, rebeccalendl is using Civi more day-to-day than I am, so I would recommend that you take them up on their kind offer and just ping me if you have any further questions. Or I'm around now if you would just like to Hangout and discuss it.
