### ISSUE TITLE
Summit Registration Landing page

### ISSUE THREAD

**Issue by mmoreshead** [cc-archive/cc-summit-2017#3]
We can't translate the form but we can translate the landing pages.  Drop verified translations here and I will create the pages.  Please do let me know what language it is too :)

**Comment by claudiorrrr** [comment]
Spanish translation:

---

Nuestra Cumbre Global reúne a la comunidad de expertos, académicos y activistas que conforman Creative Commons y su red de trabajo. La próxima Cumbre Global se llevará a cabo en Toronto, Canadá, del 28 al 30 de abril de 2017.

El intercambio y los comunes: ¿y ahora qué sigue?

La Cumbre Global de Creative Commons 2017 lanza un nuevo capítulo para el movimiento de Creative Commons. La Cumbre Global proveerá de un espacio colaborativo y divertido para que cualquier persona del mundo pueda explorar el futuro de los comunes y del intercambio para los usuarios, los creadores y los activistas. Intentaremos cambiar la narrativa, del contenido licenciado con CC, a la comunidad que crea y promueve los valores de los comunes. En el proceso, no solamente reforzaremos nuestra red actual, sino que buscaremos expandir nuestro alcance --construyendo el movimiento para tener unos Comunes más vibrantes, usables y colabortivos, centrados en la gente que lo hace posible.

¡Esperamos que pienses en unirte a nosotros este año para asumir juntos esta tarea!

¿Tienes una idea genial para una charla que te gustaría presentar? Puedes responder a nuestro llamado a charlas. La fecha límite para enviar propuestas es el 27 de enero de 2017.

Por favor, lea nuestro código de conducta. Todos los asistentes, presentadores, espónsores y voluntarios de nuestra conferencia deben cooperar para asegurarnos que hay un ambiente seguro para todos.

El costo de la entrada para la Cumbre Global 2017 es de 250USD.

La entrada incluye:

- Tres días de acceso irrestricto a todas las conferencias, incluyendo las sesiones y los oradores invitados;
- Desayuno, almuerzo y bocadillos
- Bolsa del evento
- La pre-conferencia de recepción en la noche del martes con la Fundación Hewlett

También ofrecemos una tarifa de apoyo que incluye todo lo anterior, más la posibilidad de donar 50USD para nuestro programa de becas de la Cumbre Global. La tarifa es de 300USD.

Tenemos un número limitado de becas disponibles para la comunidad de CC. Si estás aplicando para una beca, por favor no te registres aquí. En ese caso, por favor, rellena el formulario de aplicación.

Cuándo
28 de abril, 2017, 8:00 AM hasta 30 de abril, 2017 6:00 PM
Contacto
Email: summit@creativecommons.org
Tarifa de la conferencia
Registro a la Cumbre Global -     $ 250.00
Registro a la Cumbre + $50 de donación para apoyar el programa de becas     $ 300.00

**Comment by mmoreshead** [comment]
@robmyers how is that top 'english' menu item on summit.cc.org supposed to work? 

For now I've just put the link to spanish at the bottom.

**Comment by rheaplex** [comment]
It can be edited here -

https://summit.creativecommons.org/wp-admin/nav-menus.php

I added a Spanish link.

**Comment by mmoreshead** [comment]
@robmyers did you check how crowded that top menu just got?  We are thinking of having a few languages, this is going to get unwieldy fast.   Maybe I'll take it out of the top nav and just add links to the tops/bottoms of pages?  Open to advice.

**Comment by rheaplex** [comment]
I do see the problem. And sub-menus don't work in this theme. So we can't use those to organize the menus and get the top-level one to take up less space.

Do edit as needed, if you need any help give me a shout.
