### ISSUE TITLE
Summit Header is looking weird when scrolling down

### ISSUE THREAD

**Issue by little-wow** [cc-archive/cc-summit-2017#7]
<img width="1279" alt="screen shot 2017-03-14 at 11 26 47 am" src="https://cloud.githubusercontent.com/assets/7093838/23908042/3c2177d6-08a9-11e7-9725-ec151a8503ac.png">

**Comment by mmoreshead** [comment]
Oh I have no idea how to fix that, I assumed it was something that @robmyers had to do to make the big logo work?

**Comment by rheaplex** [comment]
I'll take a look. It shouldn't jump up like that.

**Comment by rheaplex** [comment]
Fixed!
